//
// Advent of Code 2015 Day 25
// Brian Green
//

package main

import (
	"fmt"
)

func getCellValue(find_row int, find_col int) {
	// example => row 6, column 6 = 27995004
	// data -> Enter the code at row 2978, column 3083. (starts at 1, not 0)
	code := 20151125
	// each code is generated by taking the previous one,
	// multiplying it by 252533,
	// and then keeping the remainder from dividing that value by 33554393
	new_row := 2
	found_cell := false
	for !found_cell {
		row := new_row
		for col := 1; col <= new_row; col++ {
			code = (code * 252533) % 33554393
			if row == find_row && col == find_col {
				found_cell = true
				break
			}
			row--
		}
		new_row++
	}

	fmt.Println("row", find_row, "column", find_col, "code", code)
}

func main() {
	getCellValue(2, 1)
	getCellValue(2, 2)
	getCellValue(3, 1)
	getCellValue(6, 6)
	getCellValue(2978, 3083)
}
