#include "readFileToString.h"
#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define DATA_FILE "day25.dat"

unsigned long get_cell_value(int find_row, int find_col) {
    // example => row 6, column 6 = 27995004
    // data -> Enter the code at row 2978, column 3083. (starts at 1, not 0)
    unsigned long code = 20151125;
    // each code is generated by taking the previous one,
    // multiplying it by 252533,
    // and then keeping the remainder from dividing that value by 33554393
    int new_row = 2;

    while (true) {
        int row = new_row;
        for (int col = 1; col <= new_row; col++) {
            code = (code * 252533) % 33554393;
            if ((row == find_row) && (col == find_col)) {
                return code;
            }
            row--;
        }
        new_row++;
    }
    return 0;
}

int day25() {
    const char *filename = DATA_FILE;
    char *fileContents = readFileToString(filename);

    if (fileContents) {

        const char outer_delimiters[] = "\n";

        char *token;
        char *outer_saveptr = NULL;

        token = strtok_r(fileContents, outer_delimiters, &outer_saveptr);

        while (token != NULL) {
            int result;
            int row;
            int column;

            result = sscanf(token,
                            "To continue, please consult the code grid in the "
                            "manual.  Enter the code at row %d, column %d.",
                            &row, &column);
            if (result == 2) {
                printf("2015 Day 25 Part 1: %lu\n",
                       get_cell_value(row, column));
            } else {
                printf("Unknown key/value %s\n", token);
            }

            token = strtok_r(NULL, outer_delimiters, &outer_saveptr);
        }
    }

    printf("2015 Day 25 Part 2: (requires 49 stars)\n");
    free(fileContents);
    return 0;
}